crm/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from django.urls import re_path as url
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

openapi_info = openapi.Info(
    title="Crm API",
    default_version="v1",
)

schema_view = get_schema_view(
    openapi_info,
    public=True,
    url=settings.SWAGGER_ROOT_URL,
    permission_classes=(permissions.AllowAny,),
)


app_name = "crm"

urlpatterns = [
    url(
        r"^healthz/$",
        TemplateView.as_view(template_name="healthz.html"),
        name="healthz",
    ),
    url(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    url(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    url(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path("api/", include("common.app_urls", namespace="common_urls")),
    path(
        "logout/", views.LogoutView.as_view(), {"next_page": "/login/"}, name="logout"
    ),
    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('', include(wagtail_urls))

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # urlpatterns = urlpatterns + static(
    #     settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    # )

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load compress %}
{% load thumbnail %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{APPLICATION_NAME}}</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %} {% endblock %}
  </head>
  <body class="main_body_bg_color">
    <div class="wrapper">

      <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">

          <a class="navbar-brand" href="{% url 'common:dashboard' %}">{{APPLICATION_NAME}}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" id="dashboard" href="{% url 'common:dashboard' %}">Dashboard</a></li>
              {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:users_list' %}">Users</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" id="accounts" href="{% url 'accounts:list' %}">Accounts</a></li>
              <li class="nav-item"><a class="nav-link" id="contacts" href="{% url 'contacts:list' %}">Contacts</a></li>
              <li class="nav-item"><a class="nav-link" id="leads" href="{% url 'leads:list' %}">Leads</a></li>
              <li class="nav-item"><a class="nav-link" id="opportunities"href="{% url 'opportunities:list' %}">Opportunities</a></li>
              <li class="nav-item"><a class="nav-link" id="cases" href="{% url 'cases:list' %}">Cases</a></li>
              <li class="nav-item"><a class="nav-link" id="documents" href="{% url 'common:doc_list' %}">Documents</a></li>
            </ul>
            <ul class="navbar-nav navbar-right my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false" >
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  {% if request.user.email != "admin@micropyramid.com" %}
                  <a class="dropdown-item" href="/change-password/"><i class="fas fa-key"></i> Change Password</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'common:profile' %}"><i class="fas fa-user"></i> Profile</a>
                  <a class="dropdown-item" href="{% url 'common:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
              </li>
            </ul>
          </div>
          {% else %}
          <a class="nav-link active ml-auto" id="dashboard" href="/dashboard/">Login</a>
          {% endif %}
        </nav>
      </header>

      <div id="mainbody" class="main_container" style="padding-top:65px;">

        {% block breadcrumb %}
        {% endblock %}

        {% block content %}
        {% endblock %}
      </div>

    </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    {% block js_block %}
    {% endblock js_block %}
    <script type="text/javascript">
      $(document).ready(function(){
          word = window.location.pathname.split('/')[1]
          if(word == ""){
            $("#dashboard").addClass('active')
          }
          else{
            $('#' + word).addClass('active')
          }
      });
    </script>
  </body>
</html>

templates/healthz.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>healthz</title>
    <style type="text/css">
      body {
        margin: 40px auto;
        max-width: 650px;
        line-height: 1.6;
        font-size: 18px;
        color: #444;
        padding: 0 10px;
        overflow-y: scroll;
      }
      h1, h2, h3 {
        line-height: 1.2
      }
      a {
        text-decoration: none;
      }
      header {
        margin-bottom: 16px;
      }
    </style>
  </head>
  <body>
    <header>
      <h1 class='topbar'>healthz</h1>
    </header>
    <hr style='margin-bottom: 32px;'></hr>
  </body>
</html>

templates/root.html
{% load static %}
{% load compress %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ settings.APPLICATION_NAME }}</title>
  <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <link href="https://cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
  <link href="https://cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css" integrity="sha256-FdatTf20PQr/rWg+cAKfl6j4/IY3oohFAJ7gVC3M34E=" crossorigin="anonymous" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />

  <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/start/jquery-ui.css" />
  <style>
    .card-body {
      padding:0;
      margin:0
    }
    .select2-container--default .select2-results__option[aria-disabled=true] {
      display: none;
    }
  </style>

  {% compress css %}
  <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
  <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap-suggest.css' %}">
  {% endcompress %}

  {% block extralinks %} {% endblock %}
</head>

<body class="main_body_bg_color">
  <div class="wrapper">
    {% block header %}
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="dropdown">

            {% if request.user.is_superuser or request.user.role == 'ADMIN' %}
            <a class="dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% else %}
            {% if request.user.has_sales_access and request.user.has_marketing_access %}
            <a class="dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% elif request.user.has_sales_access and not request.user.has_marketing_access %}
            <a class="navbar-brand" href="{% url 'common:dashboard' %}" role="button" id="dropdownMenuLink" data-toggle=""
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% elif not request.user.has_sales_access and request.user.has_marketing_access %}
            <a class="navbar-brand" href="{% url 'marketing:dashboard' %}" role="button" id="dropdownMenuLink" data-toggle=""
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% else %}
            {{''}}
            {% endif %}
            {% endif %}

          <div class="dropdown-menu mt-2" aria-labelledby="dropdownMenuLink">
            {% if user.is_superuser or user.role == 'ADMIN' %}
            <a class="dropdown-item" href="/">Sales</a>
            {% else %}
            {% if user.has_sales_access and user.has_marketing_access %}
            <a class="dropdown-item" href="/">Sales</a>
            {% elif user.has_sales_access and not user.has_marketing_access %}
            <a class="dropdown-item" href="/">Sales</a>
            {% elif not user.has_sales_access and user.has_marketing_access %}
            {% else %}
            {{''}}
            {% endif %}
            {% endif %}
          </div>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% block main_menu %}{% endblock %}

          <ul class="navbar-nav navbar-right my-2 my-lg-0">
            <li class="nav-item dropdown">
              <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
                <a class="dropdown-item" href="{% url 'common:users_list' %}">Users</a>
                {% endif %}
                {% if request.user.email != "admin@micropyramid.com" %}
                <a class="dropdown-item" href="/change-password/">Change Password</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'common:profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'common:logout' %}">Logout</a>
              </div>
            </li>
          </ul>
        </div>
        {% endif %}
      </nav>
    </header>
    {% endblock %}

    <div id="mainbody" class="main_container" style="margin-top:65px;">
      {% block breadcrumb %}
      {% endblock %}

      {% block content %}
      {% endblock %}
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

  <script defer src="https://use.fontawesome.com/releases/v5.12.1/js/all.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>

  <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>

<script src="{% static 'js/ajaxForm.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js" integrity="sha256-wfVTTtJ2oeqlexBsfa3MmUoB77wDNRPqT1Q1WA2MMn4=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha256-WqU1JavFxSAMcLP2WIOI+GB2zWmShMI82mTpLDcqFUg=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js" integrity="sha256-IkytFcY/Z/rLvRE9rYyZvybaitAWr1y2jS/+eyxXky8=" crossorigin="anonymous"></script>
<script src="https://malsup.github.io/jquery.form.js"></script>

<script src="https://cdn.ckeditor.com/4.5.4/basic/ckeditor.js"></script>

<script src="{% static 'js/bootstrap-suggest.js' %}"></script>

  {% block js_block %}{% endblock js_block %}
  <script type="text/javascript">
    $(document).ready(function () {
      word = window.location.pathname.split('/')[1];
      if (word == "") {
        $("#dashboard").addClass('active');
      }
      else {
        $('#' + word).addClass('active');
      }
      marketing_word = window.location.pathname.split('/')[2];
      if (marketing_word == "") {
        $("#marketing-dashboard").addClass('active');
      }
      // console.log(marketing_word.substring(0,7) === 'contact');
      else if (marketing_word.substring(0, 7) === "contact") {
        $("#contact").css({ 'border-bottom': '3px solid #099CBE,' });
        $(".contact_class").css('border-bottom', '3px solid #099CBE');
        marketing_word = window.location.pathname.split('/')[2]
        // console.log(marketing_word)
        // console.log(marketing_word == 'contact-list')
        // console.log(marketing_word == 'contacts')
        if (marketing_word == 'contact-list') {
          $(".contact-list").css('background', '#e5e5e5');
        }
        if (marketing_word == 'contacts') {
          $(".contacts").css('background', '#e5e5e5');
        }
      }
      else {
        $('#' + marketing_word).addClass('active')
      }
    });

  </script>
</body>

</html>

templates/root_email_template.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>

<head>
  <META http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
  <div
    style="width:100%!important;margin:0!important;padding:0!important;font-size:12px;font-family:&#39;Poppins&#39;,sans-serif;color:#45586d;background:#f9f9f9">
    <table cellpadding="0" cellspacing="0" border="0"
      style="height:auto!important;margin:0;padding:0;width:100%!important;font-family:&#39;Ubuntu&#39;,sans-serif;color:#45586d;background:#f9f9f9">
      <tr>
        <td>
          <table width="600" align="center" cellpadding="0" cellspacing="0" border="0"
            style="color:#45586d;background:#f9f9f9;margin-top:40px!important;margin-right:auto!important;margin-bottom:0!important;margin-left:auto!important;border:none;width:100%!important;max-width:600px!important">
            <tr>
              <td>
                <table style="width:600px;background:#fff;padding:0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td
                      style="text-align:center;background-color:#38abdd;height:100px;width:100%;background-position:center">
                      <div style="background:rgba(0,0,0,0.50);height:100px">
                        <div style="width:100%;float:left">
                          <h1 style="font-size:2.2rem;color:#fff;text-align:center;padding-left:30px;padding-top:10px">
                            Django CRM </h1>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr style="background:#fff">
                    <td style="text-align:center;padding:20px 15px;color:#131e26;font-weight:bold;font-size:17px">
                      <strong
                        style="margin-bottom:15px;margin-top:30px;color:#ef9a9a;font-size:1.6rem;font-weight:600;display:block">

                        {% block heading %}

                        {% endblock heading %}

                      </strong>
                      <p
                        style="color:#4f657d;font-size:1rem;font-weight:500;line-height:25px;margin-bottom:10px;margin-top:10px;text-align:center">

                        {% block subject %}

                        {% endblock subject %}

                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:0px 15px;width:100%">
                      <div><a href="#"
                          style="display:inline-block;padding:10px;text-align:left;color:#ef9a9a;font-size:1rem;font-weight:600;letter-spacing:0.7px;text-decoration:none;display:block">

                          {% block content %}

                          {% endblock content %}

                        </a></div>
                      <p style="line-height:2rem;margin-top:2rem; margin-bottom: 2rem;">

                        {% block content_body %}

                        {% endblock content_body %}

                      </p>
                      


                      
                      
                      
                      {% block button_link %}


                      {% endblock button_link %}
                    </td>
                  </tr>
                  <tr>
                    <td style="text-align:center;padding:15px;background:#ef9a9a">
                      <a style="text-decoration:none;color:#45586d;font-weight:600"></a>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>
</body>

</html>

templates/root_email_template_new.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Django Crm</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
</head>

<body
  style="width:100% !important; margin:0 !important; padding:0 !important; -webkit-text-size-adjust:none; -ms-text-size-adjust:none;font-size:12px; font-family: 'Roboto', sans-serif;color: #45586d; background: #fff; ">
  <table cellpadding="0" cellspacing="0" border="0" id="backgroundTable"
    style="height:auto !important; margin:0; padding:0; width:100% !important; font-family: 'Roboto', sans-serif;color: #45586d; background: #fff;">
    <tr>
      <td>
        <table id="contenttable" width="800" align="center" cellpadding="0" cellspacing="0" border="0"
          style="font-family: 'Roboto', sans-serif;color: #45586d; background: #dfdede; margin-top:0 !important; margin-right: auto !important; margin-bottom:0 !important; margin-left: auto !important; border:none; width: 100% !important; max-width:800px !important;border: 1px solid #ddd !important;">
          <tr>
            <td style="padding: 20px;">
              <table style="width:800px;background:#fff;padding:0;" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="padding: 45px 15px;text-align: center;color: #2f5375; font-weight: 500; font-size: 48px;">
                    <span>DjangoCrm</span>
                  </td>
                </tr>

                <tr>
                  <td style="text-align:center;font-weight: 300;color:#03759a;font-size:30px;padding-top:15px;">
                    

                    {% block heading %}
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cum exercitationem placeat assumenda aspernatur nam ut odit omnis harum dicta laboriosam.
                    {% endblock heading %}

                  </td>
                </tr>

                <tr>
                  <td style="text-align:center;font-weight: 300;padding:25px 75px;color:#000;font-size:18px;">
                    

                    {% block content_body %}
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima repellat dolores quaerat minus consequuntur quos alias illo nesciunt iure quod.
                    {% endblock content_body %}

                  </td>
                </tr>

                <tr>
                  <td style="text-align:center;padding: 15px 0;">
                    
                    {% block button_link %}
                    


                    {% endblock button_link %}

                    </a>
                  </td>
                </tr>

                <tr>
                  <td style="text-align:center;padding: 15px 0;">
                    {% block extra_content %}

                    {% endblock extra_content %}
                  </td>
                </tr>
                

                

                <tr>
                  <td style="background: #f8f8f8;padding:25px 0; text-align: center;">
                    
                    
                  </td>
                </tr>

              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>

</body>

</html>